# Config file for automatic testing at travis-ci.org

language: python

python:
  - '3.4'
  - '2.7'

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests
